"""
JizzAI build tool - one command makes everything:

    python build.py

Builds a 64-bit (x64) app: JizzAI.exe, Setup.exe and Portable.exe are all x64.
Use 64-bit Python and the "win-cpu-x64" (or other x64) llama.cpp build.

It will
  1. install missing Python packages (PyInstaller, PyQt6, pypdf)
  2. package jizzai.py into dist\\JizzAI\\JizzAI.exe (PyInstaller, no console)
  3. bundle llama.cpp (the llama-*-bin-win-*.zip) into dist\\JizzAI\\llama
  4. build  output\\JizzAI-<ver>-Setup.exe       (Inno Setup installer)
  5. build  output\\JizzAI-<ver>-Portable.exe    (Inno Setup portable extractor)
  6. build  output\\JizzAI-<ver>-Portable.zip    (portable folder, no install needed)

Put these files in one folder:  jizzai.py  build.py  jizzai.iss  make_icon.py  icon.ico
and (optional)  the llama zip  (it is found automatically).
If icon.ico is missing it is generated by make_icon.py (needs Pillow, installed automatically).

Options:
    --version 1.8.0      override the version (default: APP_VERSION in jizzai.py)
    --llama PATH         llama.cpp zip or folder (default: auto-search)
    --no-llama           do not bundle llama.cpp
    --skip-installer     skip Setup.exe / Portable.exe (needs Inno Setup)
    --skip-portable      skip the portable zip
    --no-deps            do not pip-install anything
    --clean              delete build/ and dist/ first
"""
import os, sys, re, glob, shutil, zipfile, argparse, subprocess, time, struct, platform

ROOT = os.path.dirname(os.path.abspath(__file__))
APP = "JizzAI"
MAIN = os.path.join(ROOT, "jizzai.py")
ISS = os.path.join(ROOT, "jizzai.iss")
ICON = os.path.join(ROOT, "icon.ico")
BUILD = os.path.join(ROOT, "build")
DIST = os.path.join(ROOT, "dist")
OUT = os.path.join(ROOT, "output")
APP_DIR = os.path.join(DIST, APP)


def ensure_x64():
    """JizzAI is built for 64-bit Windows (x64). PyInstaller builds for the architecture of the
    Python that runs it, so refuse to build with 32-bit (or ARM) Python."""
    bits = struct.calcsize("P") * 8
    mach = platform.machine().lower()
    if bits != 64:
        fail("32-bit Python detected. JizzAI is built as x64 - install 64-bit Python 3.10+.")
    if mach not in ("amd64", "x86_64"):
        print("   [warning] Python reports machine '%s' - the build may not be x64." % mach)
    print("   target architecture: x64 (64-bit Python, machine=%s)" % mach)


def log(msg):
    print("\n==> " + msg, flush=True)


def fail(msg):
    print("\n[ERROR] " + msg, flush=True)
    raise SystemExit(1)


def run(cmd, **kw):
    print("   $ " + " ".join('"%s"' % c if " " in c else c for c in cmd), flush=True)
    r = subprocess.run(cmd, **kw)
    if r.returncode != 0:
        fail("command failed (exit code %d)" % r.returncode)


def read_version():
    try:
        with open(MAIN, encoding="utf-8") as f:
            m = re.search(r'APP_VERSION\s*=\s*"([^"]+)"', f.read())
        if m:
            return m.group(1)
    except OSError:
        pass
    return "1.8.0"


# ------------------------------------------------------------------ icon
def ensure_icon(install=True):
    if os.path.isfile(ICON):
        return
    gen = os.path.join(ROOT, "make_icon.py")
    if not os.path.isfile(gen):
        print("   [warning] icon.ico and make_icon.py not found - building without an icon")
        return
    try:
        __import__("PIL")
    except ImportError:
        if not install:
            print("   [warning] Pillow missing - building without an icon")
            return
        run([sys.executable, "-m", "pip", "install", "--upgrade", "pillow"])
    run([sys.executable, gen], cwd=ROOT)


# ------------------------------------------------------------------ dependencies
def ensure_packages(install=True):
    need = []
    for mod, pip_name in (("PyInstaller", "pyinstaller"), ("PyQt6", "PyQt6"), ("pypdf", "pypdf")):
        try:
            __import__(mod)
        except ImportError:
            need.append(pip_name)
    if not need:
        print("   all Python packages are installed")
        return
    if not install:
        fail("missing packages: " + ", ".join(need) + "  (run: pip install " + " ".join(need) + ")")
    run([sys.executable, "-m", "pip", "install", "--upgrade"] + need)


# ------------------------------------------------------------------ llama.cpp
def find_llama(arg):
    if arg:
        if os.path.exists(arg):
            return arg
        fail("llama path not found: " + arg)
    if os.path.isfile(os.path.join(ROOT, "llama", "llama-server.exe")):
        return os.path.join(ROOT, "llama")
    home = os.path.expanduser("~")
    found = []
    for d in (ROOT, os.path.join(ROOT, "llama"), os.path.join(home, "Downloads"),
              os.path.join(home, "Desktop")):
        for pat in ("llama-*bin-win*.zip", "llama*win*.zip"):
            found += glob.glob(os.path.join(d, pat))
    if not found:
        return None
    found = set(found)
    x64 = [f for f in found if "x64" in os.path.basename(f).lower() or "amd64" in os.path.basename(f).lower()]
    return max(x64 or found, key=os.path.getmtime)   # prefer the x64 build


def prepare_llama(src, stage):
    """Extract/copy llama.cpp into `stage` so that llama-server.exe sits at its top level."""
    tmp = stage + "_tmp"
    for d in (stage, tmp):
        shutil.rmtree(d, ignore_errors=True)
    if os.path.isdir(src):
        shutil.copytree(src, tmp)
    else:
        with zipfile.ZipFile(src) as z:
            z.extractall(tmp)
    root = None
    for dp, _dn, fn in os.walk(tmp):
        if "llama-server.exe" in fn:
            root = dp
            break
    if not root:
        shutil.rmtree(tmp, ignore_errors=True)
        fail("llama-server.exe not found inside: " + src)
    shutil.copytree(root, stage)
    shutil.rmtree(tmp, ignore_errors=True)
    size = sum(os.path.getsize(os.path.join(dp, f)) for dp, _d, fs in os.walk(stage) for f in fs)
    print("   llama.cpp ready (%.1f MB): %s" % (size / 1048576, stage))
    return stage


# ------------------------------------------------------------------ PyInstaller
def build_exe():
    cmd = [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", "--windowed",
           "--onedir", "--noupx", "--name", APP, "--distpath", DIST,
           "--workpath", os.path.join(BUILD, "pyinstaller"), "--specpath", BUILD,
           "--hidden-import", "pypdf"]
    for m in ("tkinter", "unittest", "pydoc", "test"):
        cmd += ["--exclude-module", m]
    if os.path.isfile(ICON):
        # --icon = exe icon, --add-data = copy next to the app so the window/taskbar icon works too
        cmd += ["--icon", ICON, "--add-data", ICON + os.pathsep + "."]
    cmd.append(MAIN)
    run(cmd, cwd=ROOT)
    if not os.path.isfile(os.path.join(APP_DIR, APP + ".exe")):
        fail("PyInstaller did not produce %s.exe (are you building on Windows?)" % APP)


# ------------------------------------------------------------------ Inno Setup
def find_iscc():
    cands = []
    if os.environ.get("ISCC"):
        cands.append(os.environ["ISCC"])
    for name in ("ISCC", "iscc"):
        w = shutil.which(name)
        if w:
            cands.append(w)
    try:
        import winreg
        subs = (r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall",
                r"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall")
        for hive in (winreg.HKEY_LOCAL_MACHINE, winreg.HKEY_CURRENT_USER):
            for sub in subs:
                for ver in ("7", "6", "5"):
                    try:
                        with winreg.OpenKey(hive, sub + "\\Inno Setup %s_is1" % ver) as k:
                            loc, _ = winreg.QueryValueEx(k, "InstallLocation")
                            cands.append(os.path.join(loc, "ISCC.exe"))
                    except OSError:
                        pass
    except ImportError:
        pass
    bases = [os.environ.get("ProgramFiles(x86)"), os.environ.get("ProgramFiles"),
             os.path.join(os.environ.get("LOCALAPPDATA", ""), "Programs")]
    for b in bases:
        if b:
            for ver in ("7", "6", "5"):
                cands.append(os.path.join(b, "Inno Setup " + ver, "ISCC.exe"))
    for c in cands:
        if c and os.path.isfile(c):
            return c
    return None


def build_installers(version):
    iscc = find_iscc()
    if not iscc:
        fail("Inno Setup (ISCC.exe) not found. Install it, or set the ISCC environment "
             "variable to its path, or run with --skip-installer.")
    if not os.path.isfile(ISS):
        fail("jizzai.iss not found next to build.py")
    print("   using " + iscc)
    base = [iscc, "/Q", "/DMyAppVersion=" + version]
    run(base + [ISS], cwd=ROOT)                      # Setup.exe
    run(base + ["/DPortable", ISS], cwd=ROOT)        # Portable.exe


# ------------------------------------------------------------------ portable zip
def build_portable_zip(version):
    os.makedirs(OUT, exist_ok=True)
    folder = "%s-Portable" % APP
    zpath = os.path.join(OUT, "%s-%s-Portable.zip" % (APP, version))
    if os.path.exists(zpath):
        os.remove(zpath)
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for dp, _dn, fns in os.walk(APP_DIR):
            for fn in fns:
                full = os.path.join(dp, fn)
                rel = os.path.relpath(full, APP_DIR)
                z.write(full, os.path.join(folder, rel))
        z.writestr(os.path.join(folder, "portable.flag"), "JizzAI portable mode")
    return zpath


# ------------------------------------------------------------------ main
def main():
    ap = argparse.ArgumentParser(description="Build JizzAI (exe + installer + portable)")
    ap.add_argument("--version")
    ap.add_argument("--llama")
    ap.add_argument("--no-llama", action="store_true")
    ap.add_argument("--skip-installer", action="store_true")
    ap.add_argument("--skip-portable", action="store_true")
    ap.add_argument("--no-deps", action="store_true")
    ap.add_argument("--clean", action="store_true")
    args = ap.parse_args()

    t0 = time.time()
    if os.name != "nt":
        fail("Run this on Windows (the app, llama.cpp bundle and Inno Setup are Windows-only).")
    if not os.path.isfile(MAIN):
        fail("jizzai.py not found next to build.py")
    version = args.version or read_version()
    print("JizzAI build - version " + version + " (x64)")
    ensure_x64()

    if args.clean:
        log("Cleaning")
        shutil.rmtree(BUILD, ignore_errors=True)
        shutil.rmtree(DIST, ignore_errors=True)
    shutil.rmtree(APP_DIR, ignore_errors=True)
    os.makedirs(OUT, exist_ok=True)

    log("1/5  Checking Python packages + icon")
    ensure_packages(install=not args.no_deps)
    ensure_icon(install=not args.no_deps)

    log("2/5  Building JizzAI.exe (PyInstaller)")
    build_exe()

    log("3/5  Bundling llama.cpp")
    if args.no_llama:
        print("   skipped (--no-llama)")
    else:
        src = find_llama(args.llama)
        if not src:
            print("   [warning] no llama zip found - the app will ask the user for llama.cpp.\n"
                  "   Put llama-*-bin-win-*.zip next to build.py or use --llama PATH.")
        else:
            print("   source: " + src)
            stage = prepare_llama(src, os.path.join(BUILD, "llama_stage"))
            shutil.copytree(stage, os.path.join(APP_DIR, "llama"))

    outputs = []
    if args.skip_installer:
        log("4/5  Installer skipped")
    else:
        log("4/5  Building Setup.exe + Portable.exe (Inno Setup)")
        build_installers(version)
        for n in ("Setup", "Portable"):
            outputs.append(os.path.join(OUT, "%s-%s-%s.exe" % (APP, version, n)))

    if args.skip_portable:
        log("5/5  Portable zip skipped")
    else:
        log("5/5  Building portable zip")
        outputs.append(build_portable_zip(version))

    log("Done in %.0f s" % (time.time() - t0))
    for p in outputs:
        if os.path.isfile(p):
            print("   %-48s %7.1f MB" % (os.path.relpath(p, ROOT), os.path.getsize(p) / 1048576))
    print("   folder: " + OUT)
    if hasattr(os, "startfile"):
        try:
            os.startfile(OUT)
        except OSError:
            pass


if __name__ == "__main__":
    try:
        main()
    finally:
        # double-clicked from Explorer (no interactive shell): keep the window open
        if len(sys.argv) == 1 and "PROMPT" not in os.environ:
            try:
                input("\nPress Enter to close...")
            except EOFError:
                pass
